FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY app.js /usr/share/nginx/html/app.js
COPY admin.html /usr/share/nginx/html/admin.html
COPY admin.js /usr/share/nginx/html/admin.js
COPY api-client.js /usr/share/nginx/html/api-client.js
COPY style.css /usr/share/nginx/html/style.css
EXPOSE 80
